version: "3"

x-env: &x-env
  - PGUSER=postgres
  - PGPASSWORD=password
  - PGDATABASE=hello_dev

services:
  database:
    image: postgres:13
    environment: *x-env

  webapp:
    tty: true
    build:
      context: .
    volumes:
      - .:/opt/app
    environment: *x-env
    command: ["bash", "start.sh"]
    depends_on:
      - database
    ports:
      - "4000:4000"
